### ISSUE TITLE
Editing Existing Recipe

### ISSUE THREAD

**Issue by sierracircle** [bskp/rezepte#1]
Hi. Is it possible to edit an existing recipe from within the app?
It looks very impressive.

**Comment by bskp** [comment]
Yes indeed! Right-click on the recipe page, and the markdown-based editor opens. Consequently, this does only work on desktops for now…
Did you run it yourself or are you visiting rezept.ee?

**Comment by sierracircle** [comment]
That works! I can right-click on a recipe and it opens for editing. 

I am running this on my webserver. It took me a while to figure out, but once I set it up properly it works fine.
Thanks for sharing this great app!
